apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  labels:
    app: customer-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: customer-service-app
  template:
    metadata:
      labels:
        app: customer-service-app
    spec:
      containers:
      - name: customerservice
        image: customerservice:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9050
---
apiVersion: v1
kind: Service
metadata:
  name: customerservice
  labels:
    app: customer-service-app
spec:
  selector:
    app: customer-service-app
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.